# Use an official Node.js runtime as a base image
FROM node:18-alpine AS build

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install -g npm@10.4.0 --ignore-scripts

# Copy the entire application code to the working directory
COPY . .

# Build the React application
RUN npm run build

# Use a smaller base image for the final container
FROM nginx:alpine

# Copy the built artifacts from the build stage to the nginx web server directory
COPY --from=build /app/build /usr/share/nginx/html

# Expose the port that the Nginx server will run on
EXPOSE 80

# The CMD instruction sets the command to run when the container starts
CMD ["nginx", "-g", "daemon off;"]
